### ISSUE TITLE
Peer to Peer Morning session Review

### ISSUE THREAD

**Issue by SaboorSohaib** [MindPrepDev/work-folio#6]
Hi Dear🎉🎉

- Your code is clean and understandable.

- Try to use more animations and transitions.

Happy coding👏👏👏👏

**Comment by AbayomiOlaoye** [comment]
Thanks @SaboorSohaib,

I did implement this recommendation by adding some animations to an svg image as background and all buttons.

_*It really looks good, thank you*_

> Just in case you would like to see the live version of the portfolio, you can follow this [link](https://abayomiolaoye.github.io)
